"""add replis to post

Revision ID: ce72510fd3e4
Revises: 
Create Date: 2025-04-06 15:05:13.074769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce72510fd3e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_to_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_reply_to_post', 'post', ['reply_to_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reply_to_post', type_='foreignkey')
        batch_op.drop_column('reply_to_id')

    # ### end Alembic commands ###
